# Generated by Django 4.1.5 on 2023-01-30 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Femeninas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("fragancia", models.CharField(max_length=200)),
                ("tamanio", models.CharField(max_length=10)),
                ("autor", models.CharField(max_length=30)),
                ("precio", models.CharField(max_length=30)),
                ("fecha", models.DateField()),
                ("detalles", models.TextField(verbose_name=200)),
            ],
        ),
        migrations.CreateModel(
            name="Infantiles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("fragancia", models.CharField(max_length=200)),
                ("tamanio", models.CharField(max_length=10)),
                ("autor", models.CharField(max_length=30)),
                ("precio", models.CharField(max_length=30)),
                ("fecha", models.DateField()),
                ("detalles", models.TextField(verbose_name=200)),
            ],
        ),
        migrations.CreateModel(
            name="Masculinas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("fragancia", models.CharField(max_length=200)),
                ("tamanio", models.CharField(max_length=10)),
                ("autor", models.CharField(max_length=30)),
                ("precio", models.CharField(max_length=30)),
                ("fecha", models.DateField()),
                ("detalles", models.TextField(verbose_name=200)),
            ],
        ),
    ]
