# Generated by Django 4.1.5 on 2023-01-30 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("perfuApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="femeninas",
            name="usuario",
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name="infantiles",
            name="usuario",
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name="masculinas",
            name="usuario",
            field=models.SlugField(null=True, unique=True),
        ),
    ]
