# Generated by Django 4.1.4 on 2023-02-03 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('perfuApp', '0002_femeninas_usuario_infantiles_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='femeninas',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='infantiles',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='masculinas',
            name='usuario',
        ),
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='avatares')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
